"""
Comprehensive Concept Expansion Dictionary
Auto-generated from evaluation data analysis.
Maps food description terms to BLS catalog search terms.
"""

CONCEPT_EXPANSION = {
    "agavendicksaft": ["ahornsirup agavendicksaft"],
    "alkoholfreies bier": ["bier alkoholfrei"],
    "alpro": ["sojadrink flüssig"],
    "apfelessig": ["essig"],
    "apfelsaft": ["apfel fruchtsaft"],
    "apfelschorle": ["apfelsaftschorle"],
    "ayran": ["ayran joghurtgetränk"],
    "balsamico": ["balsamicoessig"],
    "basmatireis": ["reis geschält gekocht"],
    "bauernbrot": ["graubrot"],
    "beilagensalat": ["rohkostsalat essigmarinade"],
    "blaubeeren": ["heidelbeere roh"],
    "blumenkohl": ["blumenkohl gegart"],
    "bolognese": ["hackfleischsoße bolognese"],
    "bowl": ["reis gemüse salat", "gemüsereis", "reissalat"],
    "bratkartoffeln": ["bratkartoffeln kartoffel gebraten"],
    "bratwurst": ["bratwurst"],
    "breze": ["laugenbrezel salz"],
    "brezel": ["laugenbrezel salz"],
    "brokkoli": ["broccoli gegart"],
    "brombeeren": ["brombeere roh"],
    "bulgur": ["bulgur"],
    "burger": ["cheeseburger", "hamburger"],
    "burrito": ["wrap gefüllt tortilla"],
    "buttermilch": ["buttermilch"],
    "cappucchino": ["cappuccino"],
    "cappuccino": ["cappuccino"],
    "cashewkerne": ["cashewnuss roh"],
    "cashews": ["cashewnuss roh"],
    "champignons": ["champignon gedünstet", "zuchtpilz"],
    "cheese burger": ["cheeseburger"],
    "cheeseburger": ["cheeseburger"],
    "cherrytomaten": ["tomate rot roh"],
    "chiasamen": ["leinsamen chiasamen chia"],
    "cocktailtomaten": ["tomate rot roh"],
    "cola light": ["colagetränke kalorienarm"],
    "cola zero": ["colagetränke kalorienarm"],
    "couscous": ["couscous"],
    "curry": ["curryreis currygemüse"],
    "datteltomaten": ["tomate rot roh"],
    "dinkelbrot": ["graubrot", "dinkelbrot"],
    "dinkelbrötchen": ["brötchen"],
    "dinkelflocken": ["hafer flocken", "getreideflocken"],
    "dinkeltoast": ["weißbrot toastbrot"],
    "dinkelvollkornbrot": ["vollkornbrot"],
    "döner": ["döner kebab", "fladenbrot gefüllt grillfleisch"],
    "edamame": ["sojabohne grün"],
    "ei": ["hühnerei vollei gekocht"],
    "eier": ["hühnerei vollei gekocht"],
    "eis": ["speiseeis", "milchspeiseeis", "eiscreme", "eis gemischt"],
    "eisbergsalat": ["eisbergsalat roh"],
    "eiskaffee": ["kaffee getränk eis"],
    "eiweißbrot": ["eiweißbrot proteinbrot"],
    "eiweißpulver": ["eiweißpulver proteinpulver"],
    "erdbeeren": ["erdbeere roh"],
    "erdnüsse": ["erdnuss roh"],
    "falafel": ["falafel kichererbse"],
    "feldsalat": ["feldsalat roh"],
    "fencheltee": ["tee getränk", "kräutertee"],
    "filterkaffee": ["kaffee getränk"],
    "früchtetee": ["tee getränk", "früchtetee"],
    "frühlingszwiebel": ["lauchzwiebel roh"],
    "garnelen": ["garnele"],
    "gekochte eier": ["hühnerei vollei gekocht"],
    "gekochter schinken": ["schwein vorder hinterschinken"],
    "gekochtes ei": ["hühnerei vollei gekocht"],
    "gemischter salat": ["rohkostsalat essigmarinade"],
    "getreidekaffee": ["kaffee-ersatz getränk"],
    "glühwein": ["glühwein"],
    "grüner tee": ["tee grün getränk"],
    "grüntee": ["tee grün getränk"],
    "guacamole": ["avocado roh"],
    "gulasch": ["rindergulasch"],
    "gummibärchen": ["geleefrüchte", "gummibonbon fruchtgummi"],
    "hackfleisch": ["hackfleisch gemischt"],
    "haferdrink": ["sojadrink flüssig", "haferdrink"],
    "haferflocken": ["hafer flocken"],
    "hafermilch": ["sojadrink flüssig", "haferdrink", "pflanzenmilch"],
    "hagebuttentee": ["tee getränk"],
    "halloumi": ["halloumi"],
    "hanfsamen": ["leinsamen hanfsamen"],
    "haribo": ["geleefrüchte", "gummibonbon fruchtgummi"],
    "hartgekochtes ei": ["hühnerei vollei gekocht"],
    "harzer käse": ["harzer käse sauermilchkäse"],
    "haselnüsse": ["haselnuss roh"],
    "heidelbeeren": ["heidelbeere roh"],
    "himbeeren": ["himbeere roh"],
    "hirtenkäse": ["feta"],
    "honig": ["honig bienenhonig"],
    "hummus": ["kichererbsen gekocht", "kichererbsenmus"],
    "hähnchen": ["hähnchenbrustfilets gebraten"],
    "hähnchenbrust": ["hähnchenbrust brustfilet"],
    "hüttenkäse": ["körniger frischkäse"],
    "ingwertee": ["tee getränk"],
    "kaffee mit hafermilch": ["kaffee milch getränk"],
    "kaffee mit mandelmilch": ["kaffee milch getränk"],
    "kaffee mit milch": ["kaffee milch getränk"],
    "kaffee schwarz": ["kaffee getränk"],
    "kakao": ["schokolade heißes getränk", "kakaopulver"],
    "kamillentee": ["tee getränk", "kräutertee"],
    "karotte": ["karotte mohrrübe möhre roh"],
    "karotten": ["karotte mohrrübe möhre roh"],
    "kartoffelsalat": ["kartoffelsalat"],
    "kefir": ["kefir fett"],
    "ketchup": ["tomatenketchup"],
    "kimchi": ["sauerkraut abgetropft", "kohl fermentiert"],
    "kirschtomaten": ["tomate rot roh"],
    "kloß": ["kartoffelkloß gekocht"],
    "klöße": ["kartoffelkloß gekocht"],
    "knoblauch": ["knoblauch roh"],
    "knäckebrot": ["knäckebrote"],
    "kochschinken": ["schwein vorder hinterschinken"],
    "kohlrabi": ["kohlrabi roh"],
    "kokosmilch": ["kokosmilch", "kokosnuss"],
    "kondensmilch": ["kondensmilch kondenssahne"],
    "krapfen": ["berliner krapfen pfannkuchen hefeteig"],
    "kräutertee": ["tee getränk", "kräutertee"],
    "käse": ["schnittkäse"],
    "kürbiskernbrötchen": ["brötchen mehrkornbrötchen"],
    "kürbiskerne": ["kürbiskern roh"],
    "lachs": ["lachs salm"],
    "lachsschinken": ["schwein lachsschinken"],
    "latte macchiato": ["latte macchiato"],
    "laugenbrötchen": ["laugengebäck"],
    "leberkäse": ["fleischkäse"],
    "leberwurst": ["leberwurst"],
    "leitungswasser": ["trinkwasser"],
    "lymphtee": ["tee getränk"],
    "magerquark": ["quark fett"],
    "magnum": ["milchspeiseeis", "speiseeis schokolade"],
    "mandeldrink": ["sojadrink flüssig"],
    "mandelmilch": ["sojadrink flüssig", "mandeldrink", "pflanzenmilch"],
    "mandeln": ["mandel süß roh"],
    "marmelade": ["konfitüre marmelade"],
    "matcha latte": ["tee grün getränk milch"],
    "mehrkornbrötchen": ["brötchen mehrkornbrötchen"],
    "milch": ["kuhmilch fett"],
    "milchkaffee": ["kaffee milch getränk"],
    "milchreis": ["milchreis zucker zimt"],
    "mineralwasser": ["trinkwasser", "mineralwasser"],
    "minigurke": ["gurke roh"],
    "mischbrot": ["graubrot"],
    "miso": ["miso sojabohnenpaste"],
    "möhre": ["karotte mohrrübe möhre roh"],
    "möhren": ["karotte mohrrübe möhre roh"],
    "nudeln": ["teigwaren eifrei"],
    "nudeln gekocht": ["teigwaren eifrei gekocht"],
    "nutella": ["nuss-nougat-creme süß", "nuss nougat creme"],
    "oatly": ["sojadrink flüssig", "haferdrink"],
    "orangensaft": ["orange fruchtsaft"],
    "paprika": ["gemüsepaprika rot roh", "paprikaschote"],
    "pesto": ["basilikumpesto"],
    "petersilie": ["petersilienblatt frisch"],
    "pfannkuchen": ["pfannkuchen eierkuchen"],
    "pfefferminztee": ["tee getränk", "kräutertee"],
    "pflanzenmilch": ["sojadrink flüssig"],
    "pizza": ["pizza"],
    "pokebowl": ["gemüsereis reissalat", "reis gemüse"],
    "pommes": ["pommes frites kartoffel"],
    "prosecco": ["sekt schaumwein"],
    "proteinpulver": ["eiweißpulver proteinpulver"],
    "proteinriegel": ["energieriegel proteinriegel"],
    "putenbrust": ["pute brust aufschnitt gepökelt"],
    "quinoa": ["quinoa gekocht"],
    "radieschen": ["radieschen roh"],
    "radler": ["bier limonade radler"],
    "ramen": ["nudelsuppe"],
    "rapsöl": ["rüböl rapsöl"],
    "reis": ["reis geschält gekocht"],
    "reismilch": ["sojadrink flüssig", "reisdrink"],
    "rispentomaten": ["tomate rot roh"],
    "roggenbrötchen": ["brötchen roggenbrötchen"],
    "roggenvollkornbrot": ["vollkornbrot"],
    "rosenkohl": ["rosenkohl gegart"],
    "rote zwiebel": ["gemüsezwiebel roh"],
    "rotwein": ["weißwein rotwein"],
    "rucola": ["rucola rauke roh"],
    "räucherlachs": ["lachs geräuchert"],
    "räucherschinken": ["schwein hinterschinken geräuchert"],
    "rührei": ["rührei"],
    "saatenbrot": ["vollkornbrot", "mehrkornbrot"],
    "sahne": ["sahne schlagsahne"],
    "salami": ["salami"],
    "salat": ["rohkostsalate", "kopfsalat", "eisbergsalat"],
    "salat bowl": ["rohkostsalat essigmarinade"],
    "salatgurke": ["gurke roh"],
    "salz und pfeffer": ["gewürze"],
    "salz, pfeffer": ["gewürze"],
    "schafskäse": ["feta schafskäse"],
    "schinken": ["schwein vorder hinterschinken"],
    "schmand": ["saure sahne schmand"],
    "schnittlauch": ["schnittlauch frisch"],
    "schokolade": ["schokolade vollmilch", "schokolade"],
    "schwarzbrot": ["vollkornbrot"],
    "schwarzer tee": ["tee schwarz fermentiert getränk"],
    "schwarzwälder schinken": ["schwein hinterschinken"],
    "sekt": ["sekt schaumwein"],
    "senf": ["senf tafelsenf"],
    "serrano schinken": ["schwein vorder hinterschinken"],
    "skyr": ["quark fett"],
    "snacktomaten": ["tomate rot roh"],
    "sojadrink": ["sojadrink flüssig"],
    "sojamilch": ["sojadrink flüssig", "sojabohne"],
    "sojasauce": ["sojasoße"],
    "sojasoße": ["sojasoße"],
    "sonnenblumenkerne": ["sonnenblumenkern roh"],
    "spaghetti": ["teigwaren eifrei spaghetti"],
    "speck": ["schwein bauchspeck"],
    "spezi": ["cola mix"],
    "spiegelei": ["spiegelei"],
    "spinat": ["spinat gekocht"],
    "sprudel": ["trinkwasser", "mineralwasser"],
    "spätzle": ["spätzle eierteigwaren"],
    "strauchtomaten": ["tomate rot roh"],
    "sushi": ["sushi reis fisch"],
    "süßstoff": ["süßstoffe"],
    "süßstofftablette": ["süßstoffe"],
    "thunfisch": ["thunfisch konserve abgetropft"],
    "tofu": ["tofu sojabohne"],
    "tomaten": ["tomate rot roh"],
    "tomatenmark": ["tomatenmark"],
    "tzatziki": ["tzatziki zaziki"],
    "vanilleeis": ["speiseeis vanille"],
    "vollkornbrötchen": ["vollkornbrötchen"],
    "vollkorntoast": ["vollkornbrot toastbrot"],
    "walnüsse": ["walnuss roh"],
    "wasser": ["trinkwasser"],
    "wasser medium": ["trinkwasser"],
    "wasser still": ["trinkwasser"],
    "weizenbrötchen": ["brötchen"],
    "weißwein": ["weißwein trocken"],
    "wildheidelbeeren": ["heidelbeere roh"],
    "wrap": ["wrap gefüllt", "tortilla gefüllt"],
    "ziegenkäse": ["ziegenmilchweichkäse feta", "feta"],
    "zitronensaft": ["zitrone fruchtsaft"],
    "zucchini": ["zucchini gegart"],
    "zucker": ["zucker haushaltszucker"],
    "zwiebel": ["gemüsezwiebel roh"],
    "zwiebeln": ["gemüsezwiebel roh"],
    # Brands → generic BLS search terms
    "snickers": ["schokolade gefüllt", "milchschokolade nougat", "schokolade gefüllt mit nüssen"],
    "mars": ["schokolade gefüllt", "milchschokolade nougat", "schokolade gefüllt mit karamell"],
    "twix": ["schokolade gefüllt", "milchschokolade gefüllt mit karamell", "keks schokolade"],
    "milka": ["schokolade vollmilch", "schokolade"],
    "oreo": ["keks sandwich", "keks butterkeks"],
    "pringles": ["kartoffelchips", "chips kartoffel"],
    "froop": ["fruchtjoghurt", "joghurt frucht"],
    "gruyère": ["hartkäse", "käse hart"],
    "gruyere": ["hartkäse", "käse hart"],
    "pepsi": ["colagetränke", "colagetränke kalorienarm"],
    "red bull": ["energydrink", "energy drink koffeinhaltig"],
    "fanta": ["limonade orange", "orangenlimonade"],
}