"""
Comprehensive Concept Expansion Dictionary
Auto-generated from evaluation data analysis.
Maps food description terms to BLS catalog search terms.
"""

CONCEPT_EXPANSION = {
    "agavendicksaft": ["ahornsirup agavendicksaft"],
    "alkoholfreies bier": ["bier alkoholfrei"],
    "alpro": ["sojadrink flüssig"],
    "apfelessig": ["essig"],
    "apfelsaft": ["apfel fruchtsaft"],
    "apfelschorle": ["apfelsaftschorle"],
    "ayran": ["ayran joghurtgetränk"],
    "balsamico": ["balsamicoessig"],
    "basmatireis": ["reis geschält gekocht"],
    "bauernbrot": ["graubrot"],
    "beilagensalat": ["rohkostsalat essigmarinade"],
    "blaubeeren": ["heidelbeere roh"],
    "blumenkohl": ["blumenkohl gegart"],
    "bolognese": ["hackfleischsoße bolognese"],
    "bowl": ["reis gemüse salat", "gemüsereis", "reissalat"],
    "bratkartoffeln": ["bratkartoffeln kartoffel gebraten"],
    "bratwurst": ["bratwurst"],
    "breze": ["laugenbrezel salz"],
    "brezel": ["laugenbrezel salz"],
    "brokkoli": ["broccoli gegart"],
    "brombeeren": ["brombeere roh"],
    "bulgur": ["bulgur"],
    "burger": ["cheeseburger", "hamburger"],
    "burrito": ["wrap gefüllt tortilla"],
    "buttermilch": ["buttermilch"],
    "cappucchino": ["cappuccino"],
    "cappuccino": ["cappuccino"],
    "cashewkerne": ["cashewnuss roh"],
    "cashews": ["cashewnuss roh"],
    "champignons": ["champignon gedünstet", "zuchtpilz"],
    "cheese burger": ["cheeseburger"],
    "cheeseburger": ["cheeseburger"],
    "cherrytomaten": ["tomate rot roh"],
    "chiasamen": ["leinsamen chiasamen chia"],
    "cocktailtomaten": ["tomate rot roh"],
    "cola light": ["colagetränke kalorienarm"],
    "cola zero": ["colagetränke kalorienarm"],
    "couscous": ["couscous"],
    "curry": ["curryreis currygemüse"],
    "datteltomaten": ["tomate rot roh"],
    "dinkelbrot": ["graubrot", "dinkelbrot"],
    "dinkelbrötchen": ["brötchen"],
    "dinkelflocken": ["hafer flocken", "getreideflocken"],
    "dinkeltoast": ["weißbrot toastbrot"],
    "dinkelvollkornbrot": ["vollkornbrot"],
    "döner": ["döner kebab", "fladenbrot gefüllt grillfleisch"],
    "edamame": ["sojabohne grün"],
    "ei": ["hühnerei vollei gekocht"],
    "eier": ["hühnerei vollei gekocht"],
    "eis": ["speiseeis", "milchspeiseeis", "eiscreme", "eis gemischt"],
    "eisbergsalat": ["eisbergsalat roh"],
    "eiskaffee": ["kaffee getränk eis"],
    "eiweißbrot": ["eiweißbrot proteinbrot"],
    "eiweißpulver": ["eiweißpulver proteinpulver"],
    "erdbeeren": ["erdbeere roh"],
    "erdnüsse": ["erdnuss roh"],
    "falafel": ["falafel kichererbse"],
    "feldsalat": ["feldsalat roh"],
    "fencheltee": ["tee getränk", "kräutertee"],
    "filterkaffee": ["kaffee getränk"],
    "früchtetee": ["tee getränk", "früchtetee"],
    "frühlingszwiebel": ["lauchzwiebel roh"],
    "garnelen": ["garnele"],
    "gekochte eier": ["hühnerei vollei gekocht"],
    "gekochter schinken": ["schwein vorder hinterschinken"],
    "gekochtes ei": ["hühnerei vollei gekocht"],
    "gemischter salat": ["rohkostsalat essigmarinade"],
    "getreidekaffee": ["kaffee-ersatz getränk"],
    "glühwein": ["glühwein"],
    "grüner tee": ["tee grün getränk"],
    "grüntee": ["tee grün getränk"],
    "guacamole": ["avocado roh"],
    "gulasch": ["rindergulasch"],
    "gummibärchen": ["geleefrüchte", "gummibonbon fruchtgummi"],
    "hackfleisch": ["hackfleisch gemischt"],
    "haferdrink": ["sojadrink flüssig", "haferdrink"],
    "haferflocken": ["hafer flocken"],
    "hafermilch": ["sojadrink flüssig", "haferdrink", "pflanzenmilch"],
    "hagebuttentee": ["tee getränk"],
    "halloumi": ["halloumi"],
    "hanfsamen": ["leinsamen hanfsamen"],
    "haribo": ["geleefrüchte", "gummibonbon fruchtgummi"],
    "hartgekochtes ei": ["hühnerei vollei gekocht"],
    "harzer käse": ["harzer käse sauermilchkäse"],
    "haselnüsse": ["haselnuss roh"],
    "heidelbeeren": ["heidelbeere roh"],
    "himbeeren": ["himbeere roh"],
    "hirtenkäse": ["feta"],
    "honig": ["honig bienenhonig"],
    "hummus": ["kichererbsen gekocht", "kichererbsenmus"],
    "hähnchen": ["hähnchenbrustfilets gebraten"],
    "hähnchenbrust": ["hähnchenbrust brustfilet"],
    "hüttenkäse": ["körniger frischkäse"],
    "ingwertee": ["tee getränk"],
    "kaffee mit hafermilch": ["kaffee milch getränk"],
    "kaffee mit mandelmilch": ["kaffee milch getränk"],
    "kaffee mit milch": ["kaffee milch getränk"],
    "kaffee schwarz": ["kaffee getränk"],
    "kakao": ["schokolade heißes getränk", "kakaopulver"],
    "kamillentee": ["tee getränk", "kräutertee"],
    "karotte": ["karotte mohrrübe möhre roh"],
    "karotten": ["karotte mohrrübe möhre roh"],
    "kartoffelsalat": ["kartoffelsalat"],
    "kefir": ["kefir fett"],
    "ketchup": ["tomatenketchup"],
    "kimchi": ["sauerkraut abgetropft", "kohl fermentiert"],
    "kirschtomaten": ["tomate rot roh"],
    "kloß": ["kartoffelkloß gekocht"],
    "klöße": ["kartoffelkloß gekocht"],
    "knoblauch": ["knoblauch roh"],
    "knäckebrot": ["knäckebrote"],
    "kochschinken": ["schwein vorder hinterschinken"],
    "kohlrabi": ["kohlrabi roh"],
    "kokosmilch": ["kokosmilch", "kokosnuss"],
    "kondensmilch": ["kondensmilch kondenssahne"],
    "krapfen": ["berliner krapfen pfannkuchen hefeteig"],
    "kräutertee": ["tee getränk", "kräutertee"],
    "käse": ["schnittkäse"],
    "kürbiskernbrötchen": ["brötchen mehrkornbrötchen"],
    "kürbiskerne": ["kürbiskern roh"],
    "lachs": ["lachs salm"],
    "lachsschinken": ["schwein lachsschinken"],
    "latte macchiato": ["latte macchiato"],
    "laugenbrötchen": ["laugengebäck"],
    "leberkäse": ["fleischkäse"],
    "leberwurst": ["leberwurst"],
    "leitungswasser": ["trinkwasser"],
    "lymphtee": ["tee getränk"],
    "magerquark": ["quark fett"],
    "magnum": ["milchspeiseeis", "speiseeis schokolade"],
    "mandeldrink": ["sojadrink flüssig"],
    "mandelmilch": ["sojadrink flüssig", "mandeldrink", "pflanzenmilch"],
    "mandeln": ["mandel süß roh"],
    "marmelade": ["konfitüre marmelade"],
    "matcha latte": ["tee grün getränk milch"],
    "mehrkornbrötchen": ["brötchen mehrkornbrötchen"],
    "milch": ["kuhmilch fett"],
    "milchkaffee": ["kaffee milch getränk"],
    "milchreis": ["milchreis zucker zimt"],
    "mineralwasser": ["trinkwasser", "mineralwasser"],
    "minigurke": ["gurke roh"],
    "mischbrot": ["graubrot"],
    "miso": ["miso sojabohnenpaste"],
    "möhre": ["karotte mohrrübe möhre roh"],
    "möhren": ["karotte mohrrübe möhre roh"],
    "nudeln": ["teigwaren eifrei"],
    "nudeln gekocht": ["teigwaren eifrei gekocht"],
    "nutella": ["nuss-nougat-creme süß", "nuss nougat creme"],
    "oatly": ["sojadrink flüssig", "haferdrink"],
    "orangensaft": ["orange fruchtsaft"],
    "paprika": ["gemüsepaprika rot roh", "paprikaschote"],
    "pesto": ["basilikumpesto"],
    "petersilie": ["petersilienblatt frisch"],
    "pfannkuchen": ["pfannkuchen eierkuchen"],
    "pfefferminztee": ["tee getränk", "kräutertee"],
    "pflanzenmilch": ["sojadrink flüssig"],
    "pizza": ["pizza"],
    "pokebowl": ["gemüsereis reissalat", "reis gemüse"],
    "pommes": ["pommes frites kartoffel"],
    "prosecco": ["sekt schaumwein"],
    "proteinpulver": ["eiweißpulver proteinpulver"],
    "proteinriegel": ["energieriegel proteinriegel"],
    "putenbrust": ["pute brust aufschnitt gepökelt"],
    "quinoa": ["quinoa gekocht"],
    "radieschen": ["radieschen roh"],
    "radler": ["bier limonade radler"],
    "ramen": ["nudelsuppe"],
    "rapsöl": ["rüböl rapsöl"],
    "reis": ["reis geschält gekocht"],
    "reismilch": ["sojadrink flüssig", "reisdrink"],
    "rispentomaten": ["tomate rot roh"],
    "roggenbrötchen": ["brötchen roggenbrötchen"],
    "roggenvollkornbrot": ["vollkornbrot"],
    "rosenkohl": ["rosenkohl gegart"],
    "rote zwiebel": ["gemüsezwiebel roh"],
    "rotwein": ["weißwein rotwein"],
    "rucola": ["rucola rauke roh"],
    "räucherlachs": ["lachs geräuchert"],
    "räucherschinken": ["schwein hinterschinken geräuchert"],
    "rührei": ["rührei"],
    "saatenbrot": ["vollkornbrot", "mehrkornbrot"],
    "sahne": ["sahne schlagsahne"],
    "salami": ["salami"],
    "salat": ["rohkostsalate", "kopfsalat", "eisbergsalat"],
    "salat bowl": ["rohkostsalat essigmarinade"],
    "salatgurke": ["gurke roh"],
    "salz und pfeffer": ["gewürze"],
    "salz, pfeffer": ["gewürze"],
    "schafskäse": ["feta schafskäse"],
    "schinken": ["schwein vorder hinterschinken"],
    "schmand": ["saure sahne schmand"],
    "schnittlauch": ["schnittlauch frisch"],
    "schokolade": ["schokolade vollmilch", "schokolade"],
    "schwarzbrot": ["vollkornbrot"],
    "schwarzer tee": ["tee schwarz fermentiert getränk"],
    "schwarzwälder schinken": ["schwein hinterschinken"],
    "sekt": ["sekt schaumwein"],
    "senf": ["senf tafelsenf"],
    "serrano schinken": ["schwein vorder hinterschinken"],
    "skyr": ["quark fett"],
    "snacktomaten": ["tomate rot roh"],
    "sojadrink": ["sojadrink flüssig"],
    "sojamilch": ["sojadrink flüssig", "sojabohne"],
    "sojasauce": ["sojasoße"],
    "sojasoße": ["sojasoße"],
    "sonnenblumenkerne": ["sonnenblumenkern roh"],
    "spaghetti": ["teigwaren eifrei spaghetti"],
    "speck": ["schwein bauchspeck"],
    "spezi": ["cola mix"],
    "spiegelei": ["spiegelei"],
    "spinat": ["spinat gekocht"],
    "sprudel": ["trinkwasser", "mineralwasser"],
    "spätzle": ["spätzle eierteigwaren"],
    "strauchtomaten": ["tomate rot roh"],
    "sushi": ["sushi reis fisch"],
    "süßstoff": ["süßstoffe"],
    "süßstofftablette": ["süßstoffe"],
    "thunfisch": ["thunfisch konserve abgetropft"],
    "tofu": ["tofu sojabohne"],
    "tomaten": ["tomate rot roh"],
    "tomatenmark": ["tomatenmark"],
    "tzatziki": ["tzatziki zaziki"],
    "vanilleeis": ["speiseeis vanille"],
    "vollkornbrötchen": ["vollkornbrötchen"],
    "vollkorntoast": ["vollkornbrot toastbrot"],
    "walnüsse": ["walnuss roh"],
    "wasser": ["trinkwasser"],
    "wasser medium": ["trinkwasser"],
    "wasser still": ["trinkwasser"],
    "weizenbrötchen": ["brötchen"],
    "weißwein": ["weißwein trocken"],
    "wildheidelbeeren": ["heidelbeere roh"],
    "wrap": ["wrap gefüllt", "tortilla gefüllt"],
    "ziegenkäse": ["ziegenmilchweichkäse feta", "feta"],
    "zitronensaft": ["zitrone fruchtsaft"],
    "zucchini": ["zucchini gegart"],
    "zucker": ["zucker haushaltszucker"],
    "zwiebel": ["gemüsezwiebel roh"],
    "zwiebeln": ["gemüsezwiebel roh"],

    # ── Brands → generic BLS search terms ──
    "snickers": ["schokolade gefüllt", "milchschokolade nougat", "schokolade gefüllt mit nüssen"],
    "mars": ["schokolade gefüllt", "milchschokolade nougat", "schokolade gefüllt mit karamell"],
    "twix": ["schokolade gefüllt", "milchschokolade gefüllt mit karamell", "keks schokolade"],
    "milka": ["schokolade vollmilch", "schokolade"],
    "oreo": ["keks sandwich", "keks butterkeks"],
    "pringles": ["kartoffelchips", "chips kartoffel"],
    "froop": ["fruchtjoghurt", "joghurt frucht"],
    "gruyère": ["hartkäse", "käse hart"],
    "gruyere": ["hartkäse", "käse hart"],
    "pepsi": ["colagetränke", "colagetränke kalorienarm"],
    "red bull": ["energydrink", "energy drink koffeinhaltig"],
    "fanta": ["limonade orange", "orangenlimonade"],
    # New brands from gap analysis (51 missing)
    "duplo": ["schokoriegel waffel", "waffelschnitte schokolade"],
    "hanuta": ["waffel haselnuss", "haselnussschnitte"],
    "knoppers": ["waffel milchcreme", "milchschnitte"],
    "ferrero": ["praline schokolade", "schokolade praline"],
    "ferrero rocher": ["praline haselnuss schokolade"],
    "ferrero küsschen": ["praline haselnuss"],
    "kinder": ["schokolade milchcreme", "kinderschokolade"],
    "kinder bueno": ["schokolade waffel milchcreme"],
    "kinderschokolade": ["schokolade milchcreme"],
    "kinderriegel": ["schokoriegel milchcreme"],
    "kinderpingui": ["milchschnitte schokolade"],
    "corny": ["müsliriegel", "getreideriegel"],
    "ritter sport": ["schokolade tafelschokolade"],
    "lindt": ["schokolade praline"],
    "maoam": ["kaubonbon frucht"],
    "katjes": ["fruchtgummi"],
    "trolli": ["fruchtgummi gummibonbon"],
    "nimm2": ["bonbon frucht"],
    "toffifee": ["praline karamell haselnuss"],
    "raffaello": ["praline kokos mandel"],
    "rocher": ["praline haselnuss schokolade"],
    "pick up": ["keksriegel schokolade"],
    "leibniz": ["keks butterkeks"],
    "balisto": ["schokoriegel müsli"],
    "chio": ["kartoffelchips"],
    "funny frisch": ["kartoffelchips"],
    "vitalis": ["müsli knuspermüsli"],
    "leerdammer": ["schnittkäse"],
    "bergader": ["weichkäse bergkäse"],
    "philadelphia": ["frischkäse doppelrahmstufe"],
    "exquisa": ["frischkäse quark"],
    "arla": ["skyr quark"],
    "landliebe": ["joghurt milch"],
    "weihenstephan": ["joghurt quark milch"],
    "zott": ["joghurt fruchtjoghurt"],
    "ehrmann": ["joghurt fruchtjoghurt"],
    "almighurt": ["fruchtjoghurt"],
    "bauer": ["fruchtjoghurt"],
    "actimel": ["joghurtdrink probiotisch"],
    "activia": ["joghurt probiotisch"],
    "müller": ["milchreis joghurt"],
    "alpro": ["sojadrink pflanzenmilch", "haferdrink"],
    "vemondo": ["pflanzenmilch sojadrink"],
    "kölln": ["haferflocken müsli"],
    "alnatura": ["müsli haferflocken"],
    "seitenbacher": ["müsli"],
    "kelloggs": ["cornflakes frühstückscerealien"],
    "kellogs": ["cornflakes frühstückscerealien"],
    "rügenwalder": ["wurst aufschnitt", "vegetarische wurst"],
    "herta": ["schinken aufschnitt"],
    "dulano": ["wurst salami"],
    "gutfried": ["geflügelwurst aufschnitt"],
    "wiesenhof": ["hähnchenfleisch geflügel"],
    "barilla": ["teigwaren eifrei", "pesto"],
    "wagner": ["pizza tiefkühl"],
    "meggle": ["butter streichfett"],
    "bionade": ["limonade"],
    "fritz-kola": ["colagetränk"],
    "mezzo mix": ["colagetränk mischgetränk"],
    "volvic": ["trinkwasser mineralwasser"],
    "golden toast": ["toastbrot weizen"],
    "mestemacher": ["vollkornbrot"],
    "heinz": ["ketchup tomatenketchup"],
    "hela": ["gewürzketchup"],
    "thomy": ["mayonnaise senf"],
    "develey": ["senf tafelsenf"],
    "kühne": ["essig gewürzgurken"],

    # ── Seasonal foods ──
    "osterbrot": ["hefezopf süßes brot", "osterbrot hefeteig"],
    "osterei": ["hühnerei vollei gekocht", "schokoladenei"],
    "osterhase": ["schokolade figur", "schokolade vollmilch"],
    "schokoweihnachtsmann": ["schokolade figur", "schokolade vollmilch"],
    "weihnachtsmann": ["schokolade figur", "schokolade vollmilch"],
    "christstollen": ["stollen weihnachtsstollen", "rosinenstollen"],
    "stollen": ["stollen weihnachtsstollen", "rosinenstollen"],
    "lebkuchen": ["lebkuchen oblaten", "lebkuchen nürnberger"],
    "elisenlebkuchen": ["lebkuchen oblaten nürnberger"],
    "lebkuchenkonfekt": ["lebkuchen konfekt"],
    "spekulatius": ["spekulatius buttergebäck", "gewürzspekulatius"],
    "gewürzspekulatius": ["spekulatius gewürz buttergebäck"],
    "adventskuchen": ["stollen weihnachtsgebäck"],

    # ── Colloquial / Regional German foods ──
    "kaiserschmarrn": ["pfannkuchen eierkuchen", "kaiserschmarrn mehlspeise"],
    "käsespätzle": ["spätzle käse überbacken", "eierteigwaren käse"],
    "schupfnudeln": ["schupfnudeln kartoffelnudeln", "kartoffelteig"],
    "dampfnudeln": ["dampfnudel hefekloß", "hefeteig gedämpft"],
    "germknödel": ["hefekloß germknödel", "dampfnudel gefüllt"],
    "maultaschen": ["maultaschen teigtasche", "teigtasche fleisch spinat"],
    "maultasche": ["maultaschen teigtasche"],
    "flammkuchen": ["flammkuchen elsässer", "pizza dünn"],
    "kartoffelpuffer": ["kartoffelpuffer reibekuchen", "reibekuchen"],
    "reibekuchen": ["kartoffelpuffer reibekuchen"],
    "strudel": ["apfelstrudel blätterteig"],
    "apfelstrudel": ["apfelstrudel blätterteig", "strudel apfel"],
    "obatzter": ["obatzter obatzda", "frischkäse camembert"],
    "obazda": ["obatzter obatzda", "frischkäse camembert"],
    "kassler": ["kassler schwein gepökelt", "schweinekotelett geräuchert"],
    "schäufele": ["schweineschulter gebraten", "schäufele schwein"],
    "schäuferla": ["schweineschulter gebraten"],
    "pellkartoffeln": ["kartoffel gekocht schale", "kartoffeln gegart"],
    "salzkartoffeln": ["kartoffeln gekocht gesalzen", "kartoffeln gegart"],
    "bratkartoffeln": ["kartoffeln gebraten"],
    "röstzwiebeln": ["zwiebel geröstet gebraten"],
    "sauerkraut": ["sauerkraut weinsauerkraut"],
    "krautsalat": ["weißkrautsalat krautsalat"],
    "currywurst": ["bratwurst currysoße", "currywurst"],
    "weißwurst": ["weißwurst brühwurst"],

    # ── International foods ──
    "gnocchi": ["gnocchi kartoffel", "kartoffelklöße italienisch"],
    "gyros": ["gyros schweinefleisch", "grillfleisch gewürzt"],
    "hähnchengyros": ["hähnchenfleisch gyros gewürzt"],
    "souvlaki": ["grillfleisch spieß schwein"],
    "bifteki": ["frikadelle griechisch hackfleisch"],
    "döner": ["döner kebab", "fladenbrot gefüllt grillfleisch"],
    "dönerfleisch": ["grillfleisch kebab gewürzt"],
    "dürüm": ["wrap döner fladenbrot"],
    "falafel": ["falafel kichererbse frittiert"],
    "pho": ["nudelsuppe reisnudeln vietnamesisch"],
    "pho suppe": ["nudelsuppe reisnudeln vietnamesisch"],
    "pad thai": ["reisnudeln gebraten thai"],
    "ramen": ["nudelsuppe asiatisch"],
    "ramensuppe": ["nudelsuppe asiatisch"],
    "naan": ["fladenbrot naan indisch"],
    "naan brot": ["fladenbrot naan indisch"],
    "focaccia": ["fladenbrot focaccia olivenöl"],
    "bruschetta": ["brot geröstet tomate knoblauch"],
    "ciabatta": ["weißbrot ciabatta italienisch"],
    "tiramisu": ["tiramisu mascarpone löffelbiskuit"],
    "panna cotta": ["panna cotta sahne dessert"],
    "mochi": ["reiskuchen süß japanisch"],
    "sushi": ["sushi reis fisch", "reisrolle fisch"],
    "sushireis": ["reis gekocht sushi", "klebreis"],
    "shakshuka": ["eierspeise tomate paprika"],
    "calzone": ["pizza gefüllt calzone"],
    "risotto": ["reis risotto gekocht"],
    "gemüserisotto": ["reis risotto gemüse"],
    "linsenrisotto": ["reis risotto linsen"],
    "antipasti": ["gemüse eingelegt öl", "antipasti"],
    "taboule": ["bulgursalat taboulé petersilie"],
    "kimchi": ["sauerkraut abgetropft", "kohl fermentiert"],
    "cevapici": ["hackfleisch gegrillt cevapcici"],
    "calamari": ["tintenfisch frittiert"],
    "soljanka": ["suppe fleisch sauer"],

    # ── Compound dishes with curry/wrap/bowl ──
    "linsencurry": ["linsen curry", "linsengericht gewürzt"],
    "kichererbsencurry": ["kichererbsen curry"],
    "gemüsecurry": ["gemüse curry"],
    "hähnchencurry": ["hähnchenfleisch curry"],
    "erdnusscurry": ["erdnuss curry soße"],
    "currysoße": ["currysoße"],
    "currysauce": ["currysoße"],
    "curryaufstrich": ["aufstrich curry"],
    "currygewürz": ["curry gewürz"],
    "vollkornwrap": ["wrap vollkorn tortilla"],
    "weizenwrap": ["wrap weizen tortilla"],
    "weizenwraps": ["wrap weizen tortilla"],
    "proteinwrap": ["wrap protein tortilla"],
    "wraps": ["wrap gefüllt tortilla"],
    "taco": ["taco schale mais"],
    "nacho": ["tortillachips mais"],
    "salat bowl": ["rohkostsalat essigmarinade gemüse"],
    "salat-bowl": ["rohkostsalat essigmarinade gemüse"],
    "lunchbowl": ["reis gemüse salat"],
    "pokebowl": ["reis gemüse fisch salat"],
    "smoothie": ["smoothie fruchtgetränk", "obstmus fruchtpüree"],
    "milkshake": ["milchshake milch eis"],
    "milchshake": ["milchshake milch eis"],
    "protein-shake": ["eiweißpulver proteinshake milch"],
    "vanilleshake": ["milchshake vanille"],

    # ── Zero-candidate rescues (high frequency) ──
    "skyr": ["quark fett mager", "skyr isländisch"],
    "porridge": ["haferbrei haferflocken", "haferschleim"],
    "overnight oats": ["haferflocken eingeweicht", "haferbrei"],
    "ajvar": ["paprikamark gemüsepaste", "paprika aubergine paste"],
    "bacon": ["speck frühstücksspeck", "schwein bauchspeck"],
    "brownie": ["schokoladenkuchen brownie", "rührkuchen schokolade"],
    "bagel": ["brötchen bagel hefeteig"],
    "burrata": ["mozzarella frischkäse"],
    "cranberries": ["cranberry preiselbeere getrocknet"],
    "cranberry": ["cranberry preiselbeere"],
    "croutons": ["brot geröstet weißbrot"],
    "pita": ["fladenbrot pita"],
    "wedges": ["kartoffel gebacken kartoffelspalten"],
    "aroniapulver": ["aronia pulver getrocknet"],
    "flohsamenschalen": ["flohsamen schalen ballaststoff"],
    "flohsamenschalenpulver": ["flohsamen schalen pulver"],
    "flohsamen": ["flohsamen ballaststoff"],
    "berberitzen": ["berberitze getrocknet frucht"],
    "erythrit": ["süßstoff zuckerersatz"],
    "energydrink": ["energydrink koffeinhaltig"],
    "energy drink": ["energydrink koffeinhaltig"],
    "isodrink": ["sportgetränk isotonisch"],
    "isosportgetränk": ["sportgetränk isotonisch"],
    "proteinriegel": ["energieriegel proteinriegel"],
    "proteinpulver": ["eiweißpulver proteinpulver"],
    "proteincrispies": ["eiweißpulver knusper"],
    "laugenstange": ["laugengebäck laugenstange"],
    "laugenstangen": ["laugengebäck laugenstange"],
    "laugenzopf": ["laugengebäck"],
    "laugenknoten": ["laugengebäck"],
    "laugeneck": ["laugengebäck"],
    "laugeneckbrötchen": ["laugengebäck brötchen"],
    "laugenbaguette": ["laugengebäck baguette"],
    "laugendreieck": ["laugengebäck"],
    "körnerbrötchen": ["brötchen mehrkornbrötchen"],
    "körnerbaguette": ["baguette mehrkorn"],
    "weltmeisterbrötchen": ["brötchen mehrkornbrötchen"],
    "steinofenbrötchen": ["brötchen steinofen"],
    "burgerbrötchen": ["brötchen hamburgerbrötchen"],
    "frühstücksbrötchen": ["brötchen weizenbrötchen"],
    "dinkelbrötchen": ["brötchen dinkelbrötchen"],
    "basismüsli": ["müsli basis"],
    "birchermüsli": ["müsli bircher haferflocken"],
    "morgenstundmüsli": ["müsli haferflocken"],
    "morgenstundbrei": ["haferbrei porridge"],
    "bratwürste": ["bratwurst schwein"],
    "bratwürstchen": ["bratwurst klein"],
    "bockwürste": ["bockwurst"],
    "stadtwurst": ["brühwurst"],
    "kaminwurzen": ["hartwurst rohwurst"],
    "hartwurst": ["rohwurst dauerwurst"],
    "frühstückswurst": ["brühwurst aufschnitt"],
    "landleberwurst": ["leberwurst"],
    "streichleberwurst": ["leberwurst streichfähig"],
    "räuchertofu": ["tofu geräuchert"],
    "plattpfirsich": ["pfirsich roh", "pfirsich flach"],
    "plattpfirsiche": ["pfirsich roh"],
    "minigurke": ["gurke roh salatgurke"],
    "snackgurke": ["gurke roh salatgurke"],
    "bauerngurke": ["gurke roh salatgurke"],
    "schlangengurke": ["salatgurke roh"],
    "staudensellerie": ["staudensellerie roh", "stangensellerie"],
    "stangensellerie": ["staudensellerie roh", "stangensellerie"],
    "pellkartoffeln": ["kartoffel gekocht schale"],
    "pfannengemüse": ["gemüse gemischt gebraten"],
    "ofengemüse": ["gemüse gemischt gebacken"],
    "tiefkühlbeeren": ["beerenmischung tiefgefroren"],
    "tiefkühlgemüse": ["gemüse gemischt tiefgefroren"],
    "pflanzenfett": ["pflanzenfett kokosfett"],
    "pflanzenmargarine": ["margarine pflanzlich"],
    "stapelchips": ["kartoffelchips"],
    "pommbären": ["kartoffelsnack"],
    "mozartkugeln": ["praline marzipan schokolade"],
    "berglinsen": ["linse braun"],
    "pekanüsse": ["pekannuss roh"],
    "pekannüsse": ["pekannuss roh"],
    "paranüsse": ["paranuss roh"],
    "physalis": ["physalis kapstachelbeere roh"],
    "pomelo": ["grapefruit pomelo roh"],
    "gojibeeren": ["gojibeere getrocknet"],
    "thaibeeren": ["heidelbeere auslese roh"],
    "holunderschorle": ["holundersaft schorle"],
    "multisaftschorle": ["mehrfruchtsaft schorle"],
    "multivitaminschorle": ["mehrfruchtsaft schorle vitamin"],
    "sprudel": ["trinkwasser mineralwasser"],
    "sprudelwasser": ["trinkwasser mineralwasser"],
    "leitungswasser": ["trinkwasser"],
    "filterkaffee": ["bohnenkaffee getränk"],
    "eiskaffee": ["kaffee getränk eis milch"],
    "kamillentee": ["tee getränk kräutertee", "kamille"],
    "pfefferminztee": ["tee getränk kräutertee", "pfefferminze"],
    "brennesseltee": ["tee getränk kräutertee"],
    "lymphtee": ["tee getränk kräutertee"],
    "hustentee": ["tee getränk kräutertee"],
    "ingwertee": ["tee getränk ingwer"],
    "fencheltee": ["tee getränk kräutertee", "fenchel"],
    "rooibostee": ["rooibostee aufguss"],
    "matcha": ["tee grün matcha pulver"],
    "cantuccini": ["mandelgebäck cantuccini"],
    "madeleines": ["sandkuchen gebäck"],
    "plätzchen": ["plätzchen kekse buttergebäck"],
    "cheesecake": ["käsekuchen quark"],
    "lakritzschnecke": ["lakritz süßholz"],
    "kaubonbons": ["kaubonbon frucht"],
    "lachgummi": ["fruchtgummi gummibonbon"],
    "smarties": ["schokolade dragee"],
    "yogurette": ["schokoriegel erdbeer joghurt"],
    "mentos": ["bonbon kaubonbon"],
    "bounty": ["schokoriegel kokos"],
    "passata": ["tomatenmark passierte tomaten"],
    "manchego": ["hartkäse schafsmilch"],
    "pecorino": ["hartkäse schafsmilch"],
    "mairübchen": ["rübe mairübchen roh"],
    "mungosprossen": ["mungobohne sprossen roh"],
    "jalapenos": ["peperoni jalapeño scharf"],
    "peperoni": ["peperoni scharf chili"],
    "hokkaido": ["kürbis hokkaido"],
    "saatenmischung": ["saaten kerne mischung"],
    "körnermischung": ["saaten kerne mischung"],
    "kernmix": ["saaten kerne mischung"],
    "gartenkräuter": ["kräuter frisch gemischt"],
    "frühlingszwiebeln": ["lauchzwiebel roh"],
    "noriblätter": ["seetang nori algen"],
    "tonkabohne": ["gewürz vanille"],
    "spiralnudeln": ["teigwaren eifrei fusilli"],
    "hartweizennudeln": ["teigwaren hartweizengrieß"],
    "udonnudeln": ["teigwaren udon weizen"],
    "glasnudeln": ["glasnudeln mungobohne"],
    "saltgurke": ["gewürzgurke salzgurke"],
    "kapuzinerkresse": ["kresse kapuziner"],
    "hanfsamen": ["hanfsamen hanf samen"],
    "brennesselsamen": ["brennnessel samen"],
    "meerrettich": ["meerrettich roh"],
    "fondor": ["würzmittel glutamat"],
    "soffrito": ["gemüse soffritto gebraten"],
    "sofrito": ["gemüse soffritto gebraten"],
}