"""
BLS Food Code Matcher — Project Settings
=========================================
Adjust the paths in the "Paths" section below to match your setup.
Everything else can stay as-is.
"""
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR   = PROJECT_ROOT / "data"
INDEX_DIR  = PROJECT_ROOT / "indexes"

# *** ADJUST THESE 3 PATHS to where your Excel files actually are ***
# *** ADJUST THESE 3 PATHS to where your Excel files actually are ***
# *** ADJUST THESE 3 PATHS to where your Excel files actually are ***
SRC_BLS302     = PROJECT_ROOT / "BLS_3.02_import.xlsx"
SRC_BLS40      = PROJECT_ROOT / "BLS_4_0_Daten_2025_DE.xlsx"
SRC_REFERENCE  = PROJECT_ROOT / "20260108_FIT_BLS.xlsx"

# Output catalog files (auto-generated by step0)
CATALOG_302 = DATA_DIR / "bls302_catalog.parquet"
CATALOG_40  = DATA_DIR / "bls40_catalog.parquet"
EVAL_DATA   = DATA_DIR / "evaluation_set.parquet"

# FAISS index files (auto-generated by step2)
INDEX_302 = INDEX_DIR / "bls302.index"
INDEX_40  = INDEX_DIR / "bls40.index"
IDS_302   = INDEX_DIR / "bls302_ids.npy"
IDS_40    = INDEX_DIR / "bls40_ids.npy"

# ── Embedding model ───────────────────────────────────────────────
EMBEDDING_MODEL = "intfloat/multilingual-e5-small"
EMBEDDING_DIM   = 384
QUERY_PREFIX    = "query: "
PASSAGE_PREFIX  = "passage: "

# ── Claude API ────────────────────────────────────────────────────
CLAUDE_MODEL      = "claude-sonnet-4-20250514"
RETRIEVAL_TOP_K   = 20    # candidates sent to LLM re-ranker
FINAL_TOP_K       = 3     # matches returned to user

# ── BLS code structure ────────────────────────────────────────────
FOOD_GROUP_LETTERS = {
    "B": "Brot (Breads)",
    "C": "Getreide (Cereals/grains)",
    "D": "Feinbackwaren (Pastries/cakes)",
    "E": "Eier, Teigwaren (Eggs/pasta)",
    "F": "Obst (Fruits)",
    "G": "Gemüse (Vegetables)",
    "H": "Hülsenfrüchte, Nüsse (Legumes/nuts/seeds)",
    "K": "Kartoffeln (Potatoes)",
    "M": "Milch, Käse (Dairy)",
    "N": "Alkoholfreie Getränke (Non-alcoholic beverages)",
    "P": "Alkoholische Getränke (Alcoholic beverages)",
    "Q": "Fette, Öle (Fats/oils)",
    "R": "Speisezutaten (Condiments/spices)",
    "S": "Süßwaren (Sweets)",
    "T": "Fische (Fish/seafood)",
    "U": "Fleisch gegart (Meat cooked)",
    "V": "Fleisch roh, Geflügel (Meat raw/poultry)",
    "W": "Wurst (Sausages)",
    "X": "Rezepturen pflanzlich (Recipes: vegetable/carb)",
    "Y": "Rezepturen Fleisch/Fisch (Recipes: meat/fish)",
}

PROCESSING_STATES = {
    "0": "generisch/roh (generic/raw)",
    "1": "verschiedenes (various)",
    "2": "gegart (cooked generic)",
    "3": "gekocht (boiled)",
    "4": "geschmort/gedämpft (braised/steamed)",
    "5": "gedünstet (sautéed w/o fat)",
    "6": "gebacken (baked)",
    "7": "geröstet (toasted)",
    "8": "gebraten (fried w/o fat)",
    "9": "frittiert (deep-fried)",
}
